<?php

namespace GSB\mainBundle\Repository;

/**
 * familleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class familleRepository extends \Doctrine\ORM\EntityRepository
{
}
