<?php

namespace GSB\mainBundle\Repository;

/**
 * medicamentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class medicamentRepository extends \Doctrine\ORM\EntityRepository
{
}
