<?php

namespace GSB\mainBundle\Repository;

/**
 * offrirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class offrirRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOffert($IdMedicament, $idRapport, $idVisiteur){
        return $this->createQueryBuilder('u')
        ->andWhere('u.medicament = :medicament')
        ->setParameter('medicament',$IdMedicament )
        ->andWhere('u.rapport = :rapport')
        ->setParameter('rapport',$idRapport )
        ->andWhere('u.visiteur = :visiteur')
        ->setParameter('visiteur',$idVisiteur )
        ->getQuery()
        ->getOneOrNullResult();
    }
    public function findDejaOffert($IdMedicament, $idRapport, $idVisiteur){
        return (boolean)$this->createQueryBuilder('u')
        ->andWhere('u.medicament = :medicament')
        ->setParameter('medicament',$IdMedicament )
        ->andWhere('u.rapport = :rapport')
        ->setParameter('rapport',$idRapport )
        ->andWhere('u.visiteur = :visiteur')
        ->setParameter('visiteur',$idVisiteur )
        ->getQuery()
        ->getOneOrNullResult();
    }
}
