<?php

namespace GSB\mainBundle\Repository;

/**
 * praticienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class praticienRepository extends \Doctrine\ORM\EntityRepository
{
}
