<?php

namespace GSB\mainBundle\Repository;

/**
 * rapport_visiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rapport_visiteRepository extends \Doctrine\ORM\EntityRepository
{
}
